rrag/react-stockcharts

src/lib/series/AreaSeries.jsx, src/lib/series/Line.jsx, src/lib/series/LineSeries.jsx
I would to increase the stroke width on AreaSeries and LineSeries, increase too much can be very unnecessary and ugly, but i think thinner strokes can also benefit of it.
=> Add strokeWidth prop to Area and Line Series

src/lib/tooltip/index.js
ToolTipText and ToolTipTSpanLabel are useful when making custom
tooltips, so they should be made available as imports in the lib
=> Fix #143: Export ToolTip helper components

src/lib/interactive/makeInteractive.jsx
There's a redundant export default.
=> deleted redundant export default in lib/interactive/makeInteractive.jsx

docs/lib/charts/CandleStickChartWithHoverTooltip.jsx, src/lib/tooltip/HoverTooltip.jsx
This allows us to set HoverTooltip to follows a yAccessor instead of the mouse point, 2 new props were added on HoverTooltip, `chartId` and `yAccessor`, since the HoverTooltip is out of the Chart itself, i didn't had a way to get which chart to access yScale function, so i had add the `chartId` prop to refers it, and the `yAccessor` prop itself, if both props were not provided, it fallback to the mouse point default behavior, we could also add a specific property to it, i would like to hear a feedback from you.
here's some examples
Follows by mouse.
Follows by a yAccessor, e.g.: `ema50.accessor()`
Also, both svg and canvas works, and the padding limits works as well.
=> HoverTooltip followed by a yAccessor

docs/lib/charts/CandleStickChartWithZoomPan.jsx, docs/lib/page/ZoomAndPanPage.jsx, docs/md/ZOOM-AND-PAN.md, src/lib/ChartCanvas.jsx
=> Add a way to disable mouse move, pan or zoom

src/lib/EventCapture.jsx, src/lib/interactive/ClickCallback.jsx
#184 
Right click is expected, as that is what react gives from its synthetic event system
Fixed doubleclick so it does not fire a click
http://rrag.github.io/react-stockcharts/documentation.html#/edge_coordinate
The click is delayed by 300ms to determine if there is a doubleclick.
#185 
Added `onContextMenu` 
http://rrag.github.io/react-stockcharts/documentation.html#/click_callback
=> fix #184 and #185

package.json
The debug v.2.3.3 has a syntax error, which was fixed within v.2.4.1
=> Update debug module to 2.4.1

src/lib/tooltip/HoverTooltip.jsx
I forgot to create this pull requests before, so sorry about that.
I was using a custom `tooltipSVG` function, and this pull request just take the function from the props, since the default `tooltipSVG` function are already defined on `defaultProps`.
Also, i just realized that 78748ed1852a8967072c8e26c2a7f7716b2361c9 breaks my custom tooltip width and height, it was setting `backgroundShapeSVG` width and height from `bgwidth` and `bgheight` props, and now it's taken from the `pointer.bgSize`, and i am not sure yet how it works, but i think we should take a look at it to support custom tooltips.
=> Allow overwrite tooltipSVG function

src/lib/utils/ChartDataUtil.js
When testing on mobile, pinch to zoom throws error `Uncaught TypeError: chartsToPan.indexOf is not a function`.
Steps to reproduce the bug:
- Put one finger on the mobile screen
- Put a second finger on the screen and move this second finger.
- Do not move the first finger.
Because of the thrown error the render fails and the charts disappear.
This fix might not be perfect, it only prevents the render from crashing. The result behaviour might not be the one expected (zoom level reseted?).
=> HotFix pinch to zoom - issue #122 

docs/lib/charts/CandleStickChart.jsx, package.json, src/lib/series/BarSeries.jsx, src/lib/series/CandlestickSeries.jsx, src/lib/series/StackedBarSeries.jsx, src/lib/utils/barWidth.js, src/lib/utils/index.js
I came across issue #142 the other day because my data is relatively sparse and irregular but my use-case doesn't allow the use of a `discontinuousTimeScaleProvider`. The workaround described in #142 (fiddling with widthRatio) exposes too many things that should stay internal, imo.
So I tried to come up with a better solution. Initially, I just wanted to add a time interval prop to the respective series, but I figured that's an implementation detail and only applies to certain types of axes, so I instead opted for an approach where one can pass a width function to the series which allows to implement arbitrary logic to come up with a bar width. 
* The function is passed the y-scale, y-accessor and plot data.
* The current behavior is still the default by providing the respective …
=> Configurable bar width function

src/lib/utils/ChartDataUtil.js
Webpack's code compiling can cause a direct check of each.tpye === Chart to fail.
This patch converts the two functions two strings so that it does not rely on them
being the same object only functionally equivalent.
=> Modified getNewShartConfig to account for webpack bug

src/lib/utils/shallowEqual.js
Fixes the issue explained in #233, copying my explanation from that issue:
Since you don't check `hasOwnProperty` on `b`, only on `a`, the prototype methods `__ARRAY__` and `equals` are checked and the `!a.hasOwnProperty(key)` always returns true.
=> Fix shallowEqual hasOwnProperty check, issue #233

src/lib/Chart.js, src/lib/ChartCanvas.js, src/lib/annotation/Annotate.js, src/lib/annotation/Label.js, src/lib/annotation/LabelAnnotation.js, src/lib/axes/XAxis.js, src/lib/axes/YAxis.js, src/lib/coordinates/EdgeIndicator.js, src/lib/coordinates/MouseCoordinateX.js, src/lib/coordinates/MouseCoordinateY.js, src/lib/coordinates/PriceCoordinate.js, src/lib/series/BarSeries.js, src/lib/series/CandlestickSeries.js, src/lib/tooltip/OHLCTooltip.js
As part of an effort to extract project-wide propTypes into TypeScript definitions, there were numerous corrections needed. They are either:
- Props specified as required that actually aren’t because default prop values are given.
- Missing propTypes
This is the initial round of fixes, more PRs are expected.
=> Fix propTypes requirement and add some missing propTypes

src/lib/Chart.js, src/lib/GenericChartComponent.js, src/lib/interactive/utils.js, src/lib/utils/index.js
This is an update based on https://github.com/rrag/react-stockcharts/pull/348.
It's worth noting that this also removes the findItem() function. It wasn't up to spec with the native Javascript Array.prototype.find (lacking the ability to override the context of the predicate) and it wasn't being used anywhere in the codebase.
Hopefully this looks good @rrag
=> Adds find() polyfill allowing for a linear search with early exit in all browsers

src/lib/series/RSISeries.js
RSI's opacity can now be configured by the user. If not provided, it defaults to `0.3` as it was so far.
=> Added custom opacity for RSI

src/lib/scale/discontinuousTimeScaleProvider.js
See here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getYear
=> Switches to getFullYear due to getYear being deprecated on the Date class

src/lib/axes/Axis.js
Currently, the `tickInterval` option on the `XAxis` and `YAxis` expects a hard coded value which is totally unaware of the domain. 
My understanding is the `tickInterval` should force the domain to be divided in the exact number supplied by `tickInterval` hence the slight modification in code.
=> Fixed tickInterval to dynamically adapt to domain

src/lib/axes/Axis.js
So, the current code only supported `tickLabelFill` for canvas rendering. This patch adds it to the svg rendering :)
=> Added `tickLabelFill` to SVG render

docs/md/ZOOM-AND-PAN.md, src/lib/ChartCanvas.js, src/lib/scale/evaluator.js
I added the ability to clamp only the left or right sides. To do this, I made clamp a string that supports 'left', 'right', and 'both'. I added backwards compatibility for `true` values as well.
=> Clamp tweak

src/lib/ChartCanvas.js, src/lib/scale/evaluator.js
The current master didn't lint and the propType for "clamp" did not match the code (and the defaults did not match) -- both string and boolean are now accepted.
The domain change for clamping was not done in a way compatible with the plugin-const-immutable.
=> make clamping code lint, fix propType for "clamp" prop

src/lib/helper/fitWidth.js
sometimes in fluid layouts width is not calculated properly while resizing, as reflow happens before we get `clientWidth`
=> Update fitWidth handleWindowResize method

src/lib/ChartCanvas.js, src/lib/EventCapture.js
@rrag We have a use case where we display multiple stock charts in a scrollable list and we want to be able to smoothly scroll through that list. `EventCapture` was always calling `preventDefault` on the scroll event, so the scrolling would stop when the cursor entered a graph, even when the zoom and pan events were disabled. Let me know if there's a better way to do this, then I can write up some docs and add a small example.
=> Add option to disable chart interaction

src/lib/axes/Axis.js, src/lib/axes/XAxis.js, src/lib/axes/YAxis.js
This adds the ability to set the font weight, either as a number (`700`) or a string (`bold`), on both X and Y axes. Defaults to 400 (normal).
```
<XAxis ... fontWeight={100} ...  />
<YAxis ... fontWeight="bold" ... />
```
=> Axis font weight

src/lib/ChartCanvas.js, src/lib/scale/evaluator.js
Implement a case for 'clamp' ChartCanvas property as function, to use some custom clamp logic.
For example, logic to restrict scroll to left by some condition - by more data availability: if there are more data on server, then leave clampedDomain as is, and load more data on onLoadMoreData event.
Otherwise, fix clampedDomain to fit data domain left bound.
=> Implement a case for 'clamp' ChartCanvas property as function
